# Generated by Django 4.1.3 on 2023-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsellingdata',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsellingdata',
            name='quantity_discount',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='itemsellingdata',
            name='sale_discount',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
