# Generated by Django 4.1.3 on 2023-03-09 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biocalc', '0002_alter_itemsellingdata_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='product_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemsellingdata',
            name='quantity_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsellingdata',
            name='sale_discount',
            field=models.IntegerField(default=0),
        ),
    ]
