from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class FishCategory(models.Model):
    """
    Model category of fish.

    contain:
        :key name - Char Field (max_length=100).
        :key slug - Slug Field (Autogenerated from name)
    """
    name = models.CharField(
        "category", 
        max_length=100, 
        db_index=True, 
        unique=True)

    slug = models.SlugField(
        max_length=100, 
        db_index=True, 
        unique=True,
        blank=True, null=True)

    class Meta:
        verbose_name = "Fish category"
        verbose_name_plural = "Fish categories"
        ordering = ("id",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("biocalc:fishes_by_category", args=[self.slug])

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        self.slug = slugify(self.name)
        super(FishCategory, self).save(*args, **kwargs)


